### ISSUE TITLE
List of small issues to be done

### ISSUE THREAD

**Issue by anhanh11001** [Kithaeron/design-project-HomeMade#74]
App
- [x] Load order details again by ID + swipe to refresh
- [x] Add app logo
- [x] Make a delete button in the cart screen.
- [x] Update order method to just cash.
- [x] Add chef contact information and location information.
- [x] Store guest order history and load it to the "My Order" screen
- [x] Test and fix back button behavior #55 
- [x] Implement address validator
- [x] Prefill address

Web
- [ ] Set up notification to notify new order, and provide option to confirm, reject order
- [ ] Set up automation to email the chef after the order is created.
- [ ] Set up a page to insert formatted chef information.
- [x] Order status

Optional:
- [ ] Store guest information to the local database after making an order and pre-fill it later.
- [ ] Usability testing
- [ ] Release

**Comment by mmclslwsl** [comment]
For storing the guest order, it was already implemented in my last pull request.
